### ISSUE TITLE
放在centos6服务器上运行脚本出错

### ISSUE THREAD

**Issue by Nobiel** [Kxuan/mafia#1]
程序挂到nginx上，然后在终端运行startserver.sh后出现
-bash: js: command not found

**Comment by Kxuan** [comment]
额。这只是一个简单的demo。js是nodejs的一个软连接。在centos换成node或nodejs试试

startserver.sh：
```
#!/bin/bash

export NODE_PATH=node_modules:node
nodejs node
```

**Comment by Nobiel** [comment]
原来是demo啊。改成node以后可以了。不过服务器异常，无法创建房间。

2016-09-20 19:02 GMT+08:00 Xuan <notifications@github.com>:

**Comment by Kxuan** [comment]
已经做了修改，应该没有问题了。
如果你用nginx做转发的话，记得要做WebSocket转发的额外配置。

~~这东西没有聊天功能，如果你想继续开发的话，我可以把项目直接转给你。~~
